dataSources: []
dbt:
  projectDir: .
  # tag: 'piperider'

profiler:
#   table:
#     # the maximum row count to profile. (Default unlimited)
#     limit: 1000000
#     duplicateRows: false

telemetry:
  id: 797d5202107543228513f240d23e1ea9
