dataSources:
- name: fhv_dev
  type: bigquery
  dbt:
    profile: default
    target: dev
    projectDir: .
- name: fhv_prod
  type: bigquery
  dbt:
    profile: default
    target: prod
    projectDir: .
dbt:
  projectDir: .
  # tag: 'piperider'

profiler:
#   table:
#     # the maximum row count to profile. (Default unlimited)
#     limit: 1000000
#     duplicateRows: false

telemetry:
  id: 837e57aba4d444348b35a2e096e660cf
