taxi-rides-ny-pg:
  outputs:
    dev:
      connect_timeout: 10
      dbname: ny_taxy
      host: localhost
      keepalives_idle: 0
      password: root
      port: 5432
      retries: 1
      schema: taxi_rides_ny_dbt
      threads: 4
      type: postgres
      user: root
  target: dev
taxi_rides_ny_bq:
  outputs:
    dev:
      dataset: a
      job_execution_timeout_seconds: 123
      job_retries: 1
      keyfile: a
      location: US
      method: service-account
      priority: interactive
      project: a
      threads: 1
      type: bigquery
  target: dev