base:
  branch: main
  dbt:
    commands:
    - dbt deps
    - dbt build --target prod
  piperider:
    command: piperider run
target:
  branch: data-modeling
  dbt:
    commands:
    - dbt deps
    - dbt build --target dev
  piperider:
    command: piperider run
