base:
  branch: main
  dbt:
    commands:
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
target:
<<<<<<< HEAD
  branch: data-modeling
=======
>>>>>>> f3543432a7c8675151b41a10046d7a465a0dacf2
  dbt:
    commands:
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
